services:
  fastapi:
    container_name: fastapi-deploy
    build: ./multi_agent_platform
    volumes:
      - ./multi_agent_platform/plugin:/code/plugin
    ports:
      - 8080:8080
    env_file:
      - ./.env
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-deploy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
    restart: always